# Generated by Django 5.0 on 2023-12-09 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_message_commit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='contract',
        ),
        migrations.AddField(
            model_name='message',
            name='commit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.commit'),
        ),
    ]
