# Generated by Django 5.0 on 2023-12-10 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_contract_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('processed', 'Processed'), ('accepted_customer', 'Accepted Customer'), ('accepted_contractor', 'Accepted Contractor'), ('rejected', 'Rejected'), ('finished', 'Finished')], default='processed'),
        ),
    ]
