# Generated by Django 5.0 on 2023-12-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_commit_created_at_contract_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
